import React from "react";
import {
	GritwellLogo,
	ShowIcon,
	HideIcon,
	CheckIcon,
	SuccessCheck,
	BackIcon,
	StatusIcon,
	DashboardIcon,
	ClientsIcon,
	ChatsIcon,
	SettingsIcon,
	LeftMenuIcon,
	NoUserImageIcon,
	ImgUploadIcon,
	InActiveIcon,
	ActiveIcon,
	OpenEyeIcon,
	PlusIcon,
	ProfileUploadIcon,
	DotsIcon,
	SymptomAnalysisIcon,
	IntakeFormIcon,
	PdfIcon,
	MessageIcon,
	DeleteIcon,
	NoUserIcon,
	DownloadsIcon,
	UsersIcon,
	PlansIcon,
	HypothesisIcon,
	NutritionsIcon,
	SupplementsIcon,
	LifestyleIcon,
	TestIcon,
	PendingIcon,
	CloseIcon,
	RootcauseIcon,
	Diagnosisicon,
	CoredysfunctionIcon,
	GoalsIcon,
	RightIcon,
	ReadinessIcon,
	SymptomIcon,
	HealthHistoryIcon,
	FoodDiaryIcon,
	FlagIcon,
	MenuDotIcon,
	NutritionTabIcon,
	TestingTabIcon,
	SupplimentsTabIcon,
	LifestyleTabIcon,
	MessageTabIcon,
	EditIcon,
	DataDeleteIcon,
	ModalCloseIcon,
	ModalWarningIcon

} from "./icons/index";
import UploadsIcon from "./icons/upload_icon";

export const iconNames = {
	gritwell: GritwellLogo,
	showicon: ShowIcon,
	hideicon: HideIcon,
	checkicon: CheckIcon,
	success: SuccessCheck,
	back: BackIcon,
	statusicon: StatusIcon,
	dashboard: DashboardIcon,
	clients: ClientsIcon,
	chats: ChatsIcon,
	settings: SettingsIcon,
	leftMenuIcon: LeftMenuIcon,
	nousericon: NoUserImageIcon,
	uploadIcon: ImgUploadIcon,
	inactiveIcon: InActiveIcon,
	activeIcon: ActiveIcon,
	openeye: OpenEyeIcon,
	plusicon: PlusIcon,
	ProfileUpload: ProfileUploadIcon,
	DotsMenu: DotsIcon,
	SymptomAnalysis: SymptomAnalysisIcon,
	IntakeForm: IntakeFormIcon,
	Pdf: PdfIcon,
	Message: MessageIcon,
	deleteIcon: DeleteIcon,
	noclienticon: NoUserIcon,
	downloadicon: DownloadsIcon,
	uploadicon: UploadsIcon,
	usericon: UsersIcon,
	plansicon: PlansIcon,
	hypothesisicon: HypothesisIcon,
	nutritionicon: NutritionsIcon,
	supplemetsicon: SupplementsIcon,
	lifestyleicon: LifestyleIcon,
	testicon: TestIcon,
	pendingicon: PendingIcon,
	closeicon: CloseIcon,
	rootcauseicon: RootcauseIcon,
	diagnosisicon: Diagnosisicon,
	coredysfunctionIcon: CoredysfunctionIcon,
	goalsicon: GoalsIcon,
	righticon:RightIcon,
	readinessicon:ReadinessIcon,
	symptomicon:SymptomIcon,
	healthhistoryicon:HealthHistoryIcon,
	fooddiaryicon:FoodDiaryIcon,
	flagicon: FlagIcon,
	menudoticon: MenuDotIcon,
	nutritiontabicon:NutritionTabIcon,
	testingtabicon:TestingTabIcon,
	supplimentstabicon:SupplimentsTabIcon,
	lifestyletabicon:LifestyleTabIcon,
	messagetabicon:MessageTabIcon,
	editicon:EditIcon,
	datadeleteicon:DataDeleteIcon,
	modalcloseicon:ModalCloseIcon,
	modalwarningicon:ModalWarningIcon
};

export type IconProps = {
	name: keyof typeof iconNames;
};
export default function Icon({ name }: IconProps) {
	const IconComponent = iconNames[name];
	return <IconComponent />;
}