const apiEndpoint = {
  signInApi: 'login',
  getProfileApi: 'profile',
  logoutApi: 'logout',
  getRoleField: 'office/roles/',
  getRoles: 'office/roles/',
  uploadProfilePicApi: 'office/uploadProfilePic',
  deleteProfilePicApi: 'office/profilePicture/',
  getClients: 'office/clients/',
  assignmentsApi: 'office/clients/assignment',
  changePasswordApi: 'changePassword',
  addUserApi: 'office/users/',
  addUsersApi: 'office/users/',
  forgotApi: 'forgotPassword',
  verifyTokenApi: 'VerifyForgotToken',
  resetPasswordApi: 'ResetPassword',
  permissionApi: 'office/permission',
  healthCoachAssignmentApi: 'office/users/role/health_coach',
  mdAssignmentsApi: 'office/users/role/md',
  adminResetPasswordApi: 'adminResetPassword',
  intakeFormApi: 'office/clients/intake_form/',
  symptomAnalysisApi: 'office/clients/symptom_analysis/',
  editProfileApi: 'office/clients/',
  docviewer: 'office/clients/historical_tests/',
  guestLogin: 'guestLogin',
  rteBox: 'office/clients/notes/',
  nutritionApi: 'office/nutrition/',
  testingApi: 'office/test/',
  supplementsApi: 'office/supplement/',
  lifestyleApi: 'office/lifestyle/',
  uploadNutritionApi: 'office/uploadNutrition',
  uploadLifestyleApi: 'office/uploadLifeSytle',
  uploadTest: 'office/uploadTest',
  uploadSupplement: 'office/uploadSupplement',
  downloadTest: 'office/downloadTest',
  downloadSupplement: 'office/downloadSupplement',
  downloadNutrition: 'office/downloadNutrition',
  downloadLifestyle: 'office/downloadLifeStyle',
  FilterApi: 'office/masters/',

  rootcauseApi: 'office/rootCause/',
  uploadRootcause: 'office/uploadRootCause',
  downloadRootcause: 'office/downloadRootCause',

  diagnosisApi: 'office/diagnosis/',
  uploadDiagnosis: 'office/uploadDiagnosis',
  downloadDiagnosis: 'office/downloadDiagnosis',

  coredysfunctionApi: 'office/coreDysfunction/',
  uploadCoredysfunction: 'office/uploadCoreDysfunction',
  downloadCoredysfunction: 'office/downloadCoreDysfunction',

  goalsApi: 'office/goal/',
  uploadGoals: 'office/uploadGoal',
  downloadGoals: 'office/downloadGoal',

  getGlobalData: 'office/userPermissions',
  getRecentActivity: 'office/clients/recentActivities',
  getAppointments: 'office/clients/appointments',

  createHealthPlan: 'office/clients/healthplan',
  healthPlanPhases: 'office/clients/healthplan/phasesOfCare',
  phasesOfCareStatuses: 'office/clients/healthplan/statuses/phasesOfCare',
  nutritionStatuses: 'office/clients/healthplan/statuses/nutrition',
  healthPlanNutrition: 'office/clients/healthplan/nutrition',
  healthPlanNutritionDelete: 'office/clients/healthplan/nutrition',
  healthPlanTesting: 'office/clients/healthplan/testing',
  healthPlanTestingDelete: 'office/clients/healthplan/testing',
  healthPlanSuplement: 'office/clients/healthplan/supplement',
  healthPlanUnits: 'office/clients/healthplan/units',
  healthPlanSuplementDelete: 'office/clients/healthplan/supplement',
  healthPlanLifeStyle: 'office/clients/healthplan/lifestyle',
  healthPlanFrequency: 'office/clients/healthplan/frequencies',
  healthPlanLifeStyleDelete: 'office/clients/healthplan/lifestyle',
  healthPlanMessage: 'office/clients/healthplan/message',
  

  healthprofileGoals: 'office/clients/healthprofile/goals',
  healthprofileHypothesis: 'office/clients/healthprofile/hypothesis',
  healthprofileMedication: 'office/clients/healthprofile/notes/medications',
  healthprofileSuppliment: 'office/clients/healthprofile/notes/supplements',
  healthprofileTimeLine: 'office/clients/healthprofile/notes/timeline',

  healthprofileNotes: 'office/clients/healthprofile/notes',
};

export default apiEndpoint;
